name: Publish to npmjs (OIDC Trusted Publisher)

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication with npm
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed    
      - name: Install latest npm
        run: npm install -g npm@latest
        
      - name: Set package.json version from tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          npm version $TAG_VERSION --no-git-tag-version

      - name: Publish to npm (OIDC Trusted Publisher)
        run: npm publish
